### ISSUE TITLE
Question about zellij-sessionizer

### ISSUE THREAD

**Issue by korrat** [msharran/.dotfiles#1]
Hi, I came across your dotfiles when searching for an alternative to Primeagen's `tmux-sessionizer` for `zellij`.

I like your script, but I have a question about [this line](https://github.com/msharran/.dotfiles/blob/06e073f5ad8f38abe0c66e2a493ff13ac92e99a0/.local/bin/zellij-sessionizer#L27). My understanding is that it is supposed to kill the current session when it exists, but as written, the `-z` test achieves the opposite: When `${OLD_SESSION_NAME}` is empty, it calls `zellij kill-session`. Could you help me understand?

Thanks!

**Comment by msharran** [comment]
Hey, I was also experimenting on it. If I remember correctly, the script was creating nested sessions unlike tmux (which doesn't allow one). So I gave up and started using tmux again.
